interval_minutes = 1

# Type of the objects in Anytype that contain the following Properties:
# "Anytype ID" with type "Object" (space member)
# "Matrix ID" with type "Text"
anytype_to_matrix_id_map_type = "matrix_member" 

# How often to resend notifications
[renotify_interval_days]
unassigned = 7
deadline_upcoming = 3
